apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: front-nginx
spec:
  replicas: {{ .Values.nginx.replica_count }}
  selector:
    matchLabels:
      app: front-nginx
  template:
    metadata:
      labels:
        app: front-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.nginx.image_tag }}
        ports:
        - containerPort: 80