apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.nginx.ingress_host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 80